version: '2'
services:
    ecoforo2-mysql:
        container_name: ecoforo2-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/ecoforo2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ecoforo2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
